### ISSUE TITLE
请问apk怎么编译的

### ISSUE THREAD

**Issue by rpdg** [buqiyuan/uni-chat#3]
我是用 hbuilderX 的 3.1.18.20210609 版本做云打包：
1. 把项目的src文件夹拖进去，编译报很多错误。
2. 把整个项目拖进去，编译会停在第一步。
请教大佬，应该怎么才能正常编译啊？

**Comment by buqiyuan** [comment]
不是基于src打包，需要import整个项目进hbuiderx进行打包，因为我用的是vue-cli
